abstract: Total Failure
author: "Ingy d\xC3\xB6t Net <ingy@cpan.org>"
distribution_type: module
generated_by: Module::Install version 0.61
license: perl
name: orz
no_index: 
  directory: 
    - inc
    - t
requires: 
  Module::Compile: 0.16
  perl: 5.6.1
version: 0.12
