use Test::Base tests => 1;

use lib 't/lib';

BEGIN { unlink 't/lib/Testorz.pmc' }

use Testorz;

run_is module => 'pmc';

sub fix_up {
    s/(by orz) \d\.\d\d/$1 x.xx/;
    s/(Module::Compile) \d\.\d\d/$1 x.xx/;
}

__DATA__
=== Compile Testorz
--- module read_file fix_up: t/lib/Testorz.pmc
--- pmc -trim fix_up
# Generated by orz 0.11 (Module::Compile 0.15) - do not edit!
#line 1 #########((( 32-bit Checksum Validator II )))################
BEGIN { use 5.006; local (*F, $/); ($F = __FILE__) =~ s!c$!!; open(F)
or die "Cannot open $F: $!"; binmode(F, ':crlf'); if (unpack('%32N*',
$F=readline(*F)) != 0xA3E61550) { use Filter::Util::Call; my $f = $F;
filter_add(sub { filter_del(); 1 while &filter_read; $_ = $f; 1; })}}
#line 1 #############################################################
package Testorz;

sub works {
    print "This works";
}

# orz...
# 
# sub busted {
#     say "orz!";
# }
# 

sub ok {
    print "ok";
}

1;
